#ifndef __4WCOMM_INT__
#define __4WCOMM_INT__

#define STATE_4WCOMM_IDLE 1
#define STATE_4WCOMM_SEND_REQUEST_SENT 2
#define STATE_4WCOMM_SEND_REQUEST_CONFIRMED 3
#define STATE_4WCOMM_SEND_REQUEST_CONF_RECEIVED 4
#define STATE_4WCOMM_GETTING_READY_FOR_DATA 5
#define STATE_4WCOMM_DATA_TRANSMISSION 6
#define STATE_4WCOMM_DATA_TRANS_CONFIRMED 7
#define STATE_4WCOMM_DATA_TRANS_CONF_RECEIVED 8

#define STATE_4WCOMM_INIT1 9
#define STATE_4WCOMM_INIT2 10
#define STATE_4WCOMM_INIT3 11
#define STATE_4WCOMM_INIT4 12
#define STATE_4WCOMM_INIT5 13
#define STATE_4WCOMM_INIT6 14
#define STATE_4WCOMM_INIT7 15
#define STATE_4WCOMM_INIT8 16

#define DIR_4WCOMM_A1_TO_A2 1
#define DIR_4WCOMM_A2_TO_A1 2
#define DIR_4WCOMM_NONE     3

#define RECVBUF_SIZE 50
#define SENDBUF_SIZE 50

#endif
